import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClientMiniplayer } from "./components/common/Modal/Music/ClientMiniplayer";
import Sidebar from "./components/constant/Sidebar";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tidelit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center`} >
        <ReactQueryProvider>  
          <main className="w-full  min-h-screen flex flex-row justify-center  bg-gradient-to-b from-[#D80DE5] to-white bg-no-repeat bg-cover bg-center p-10 gap-2" style={{ backgroundImage: 'url("/background/fondo.png")' }}>
            
            {/* Sidebar fijo */}
            <div className="sticky top-0 self-start bg-white/50 rounded-2xl p-4 border border-gray-200">
              <Sidebar />
            </div>

         
            

            {/* Contenido */}
            <div className="w-full max-w-7xl h-full flex flex-col justify-between items-center bg-gradient-to-b from-white to-white/50 rounded-2xl border border-gray-200" >
              {children}
            </div>
          </main>
          
          {/* Componente de miniplayer */}
          <div className="fixed bottom-0 left-0 right-0 z-20 backdrop-blur-2xl  p-4">
            <ClientMiniplayer />
          </div>


        </ReactQueryProvider>        
    </body>
    </html>
  );
}
